export const FETCHING = 'FETCHING'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAIL = 'FETCH_FAIL'

export const FETCH_PLAYERS = 'FETCH_PLAYERS'
export const FETCH_PLAYER_INFO = 'FETCH_PLAYER_INFO'
export const FETCH_PLAYER_CAREER = 'FETCH_PLAYER_CAREER'
export const FETCH_PLAYER_GAMELOG = 'FETCH_PLAYER_GAMELOG'

export const FETCH_TEAMS = 'FETCH_TEAMS'
export const FETCH_TEAM_DETAIL = 'FETCH_TEAM_DETAIL'
export const FETCH_TEAM_ROSTER = 'FETCH_TEAM_ROSTER'
export const FETCH_TEAM_INFO = 'FETCH_TEAM_INFO'